version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: languagecards-api
    container_name: languagecards-api
    ports:
      - "80:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=language_cards;Username=postgres;Password=root
    depends_on:
      - db
    restart: unless-stopped
    command: >
      /bin/sh -c "
        echo 'Waiting for DB to be ready...' &&
        until pg_isready -h db -U postgres; do
          sleep 2;
        done &&
        echo 'Applying EF migrations...' &&
        dotnet ef database update --no-build &&
        echo 'Starting API...' &&
        dotnet LanguageCards.Api.dll
      "
  db:
    image: postgres:16-alpine
    container_name: languagecards-db
    ports:
      - "81:5432"
    environment:
      POSTGRES_DB: language_cards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data: